version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Rebus
    versions:
    - 6.4.1
    - 6.5.0
    - 6.5.2
    - 6.5.3
    - 6.5.4
  - dependency-name: MySql.Data
    versions:
    - 8.0.23
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
  - dependency-name: NUnit
    versions:
    - 3.13.1
  - dependency-name: Microting.eForm
    versions:
    - 4.3.4
    - 4.3.8
    - 4.3.9
  - dependency-name: AWSSDK.SQS
    versions:
    - 3.5.1.13
    - 3.5.1.14
  - dependency-name: Castle.Windsor
    versions:
    - 5.1.1
  - dependency-name: Microsoft.IdentityModel.Clients.ActiveDirectory
    versions:
    - 5.2.8
